print("Enter the value of a:")
a=int(input())
print("Enter the value of b:")
b=int(input())
print("Addition",a+b)
print("Substarction",a-b)
print("Multiply",a*b)
print("Reminder",a%b)
print("Division",a/b)
print("modulous",a//b)
