print("Enter the value of a:")
a=int(input())
print("Enter the value of b:")
b=int(input())
print("not equal to:",a!=b)
print("equal to:",a==b)
print("greater than:",a>b)
print("less than:",a<b)
print("greater than or equal to:",a>=b)
print("less than or equal to:",a<=b)